### ISSUE TITLE
z

### ISSUE THREAD

**Issue by Ameena-22** [pockemon/Microaneurysm-Detection#1]
Need microaneurysm detection results of this code

**Comment by Ameena-22** [comment]
how these curves in paper are generated

**Comment by hardikrana11** [comment]
You can look into files inside source-Code folder for getting results of our code.

**Comment by Ameena-22** [comment]
How you generate these curves in the paper. when we run the code file it
only gives an accuracy score. How these curves are generated.
plz share the code for that.
